apiVersion: v1alpha
metadata:
  name: Sauce School
  tags:
    - e2e
  build: Commit $CI_COMMIT_SHORT_SHA
files:
  - tests/integration/
suites:
  - name: "Saucy Tests"
    match: ".*.(spec|test).js$"
    settings:
      browserName: chrome
image:
  base: saucelabs/stt-cypress-mocha-node
  version: v0.1.9
sauce:
  region: us-west-1
