apiVersion: v1alpha
metadata:
  name: Sauce School
  tags:
    - e2e
  build: Commit $CI_COMMIT_SHORT_SHA
files:
  - tests/integration/
suites:
  - name: "Chrome Tests"
    match: ".*.(spec|test).js$"
    settings:
      browserName: chrome
  - name: "Firefox Tests"
    match: ".*.(spec|test).js$"
    settings:
      browserName: firefox
image:
  base: saucelabs/stt-cypress-mocha-node
  version: v0.1.17
sauce:
  region: us-west-1
