apiVersion: v1alpha
kind: Cypress
sauce:
  region: us-west-1
  metadata:
    name: Sauce School
    tags:
      - e2e
    build: Commit $CI_COMMIT_SHORT_SHA
cypress:
  configFile: cypress.json
suites:
  - name: "Chrome Tests"
    browserName: chrome
    config:
      testFiles:
        - "**/*.js"
  - name: "Firefox Tests"
    browserName: firefox
    config:
      testFiles:
        - "**/*.js"
docker:
  fileMode: copy
  image:
    name: saucelabs/stt-cypress-mocha-node
    tag: v0.2.3
